name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        run: |
          npm install
          # CORRECCIÓN: Solo el nombre del repo entre barras
          npx ng build --configuration production --base-href /PixelMD-github-profile-readme-generator/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # CORRECCIÓN: Verifica si el nombre de la carpeta es pixel-md o similar
          folder: dist/prueba/browser 
          branch: gh-pages # CORRECCIÓN: Usa una rama distinta a main